<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite data-provider-thread-count="3" name="Failed suite [All Test Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="com.saucedemo.listeners.AnnotationTransformer"/>
    <listener class-name="com.saucedemo.listeners.MethodInterceptor"/>
    <listener class-name="org.testng.reporters.EmailableReporter2"/>
    <listener class-name="org.testng.reporters.FailedReporter"/>
    <listener class-name="com.aventstack.chaintest.plugins.ChainTestListener"/>
    <listener class-name="com.saucedemo.listeners.TestListenerClass"/>
  </listeners>
  <test thread-count="5" name="SauceDemoLoginExcelTest(failed)">
    <classes>
      <class name="com.saucedemo.tests.SauceDemoLoginExcelTest">
        <methods>
          <include name="loginAndLogoutTest1" invocation-numbers="1"/>
          <include name="loginAndLogoutTest2" invocation-numbers="0"/>
          <include name="tearDown"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.saucedemo.tests.SauceDemoLoginExcelTest -->
    </classes>
  </test> <!-- SauceDemoLoginExcelTest(failed) -->
</suite> <!-- Failed suite [All Test Suite] -->
